# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[zh]
  languageCode = "zh-Hans"
  contentDir = "content/zh"
  title = "Chinese website title..."
  [zh.params]
    description = "Site description in Chinese..."
  [[zh.menu.main]]
    name = "文档"
    url = "docs/"
    weight = 20
  [[zh.menu.main]]
    name = "博客"
    url = "blog/"
    weight = 30
  [[zh.menu.main]]
    name = "下载"
    url = "https://github.com/kmesh-net/kmesh/releases"
    weight = 40

# Right Menu
  [[zh.menu.main_right]]
    name = "<i class=\"fab fa-github-alt\" style=\"color: #333; font-size: 1rem; line-height: 1.25\"></i>"
    post = ""
    url = "https://github.com/kmesh-net/kmesh"
    weight = 10

  [[zh.menu.main_right]]
    name = "<i class=\"fab fa-twitter\" style=\"color: #55acee; font-size: 1rem; line-height: 1.25\"></i>"
    post = ""
    url = "https://twitter.com/Kmesh_net"
    weight = 20

  #[[zh.menu.main_right]]
  #  name = "<i class=\"fab fa-slack\" style=\"color: #55acee; font-size: 1rem; line-height: 1.25\"></i>"
  #  post = ""
  #  url = "https://app.slack.com/client/T08PSQ7BQ/C052JRURD8V?selected_team_id=T08PSQ7BQ"
  #  weight = 30

  [[zh.menu.main_right]]
    name = "<i class=\"fab fa-weixin\" style=\"color: #55acee; font-size: 1rem; line-height: 1.25\"></i>"
    post = ""
    url = "https://blog.51cto.com/u_15127420/4992806"
    weight = 40
  
  # Documentation
  [[zh.menu.docs]]
    name = "欢迎入门"
    weight = 5
    identifier = "welcome"

  [[zh.menu.docs]]
    name = "系统架构"
    weight = 10
    identifier = "architecture"

  [[zh.menu.docs]]
    name = "快速开始"
    weight = 15
    identifier = "quickstart"

  [[zh.menu.docs]]
    name = "性能"
    weight = 20
    identifier = "performance"

  [[zh.menu.docs]]
    name = "开发指南"
    weight = 25
    identifier = "developer guide"

  [[zh.menu.docs]]
    name = "社区"
    weight = 30
    identifier = "community"
